/**
 * Icônes mises en avant à l’ouverture du picker (vie quotidienne / budget).
 * Les noms doivent exister dans ICON_CATALOG.
 */
export const ICON_CATALOG_FEATURED: readonly string[] = [
  'home',
  'apartment',
  'cottage',
  'villa',
  'garage',
  'work',
  'badge',
  'business_center',
  'account_balance',
  'account_balance_wallet',
  'savings',
  'payments',
  'credit_card',
  'attach_money',
  'euro',
  'currency_exchange',
  'receipt_long',
  'request_quote',
  'point_of_sale',
  'shopping_cart',
  'shopping_bag',
  'grocery',
  'storefront',
  'store',
  'local_mall',
  'sell',
  'restaurant',
  'local_cafe',
  'coffee',
  'fastfood',
  'local_pizza',
  'bakery_dining',
  'lunch_dining',
  'dinner_dining',
  'icecream',
  'local_bar',
  'liquor',
  'directions_car',
  'directions_bus',
  'directions_subway',
  'directions_bike',
  'train',
  'tram',
  'local_taxi',
  'flight',
  'local_gas_station',
  'ev_station',
  'two_wheeler',
  'pedal_bike',
  'school',
  'menu_book',
  'auto_stories',
  'child_care',
  'child_friendly',
  'stroller',
  'elderly',
  'pets',
  'medical_services',
  'local_hospital',
  'medication',
  'dentistry',
  'monitor_heart',
  'fitness_center',
  'self_care',
  'spa',
  'sports_soccer',
  'sports_esports',
  'pool',
  'hiking',
  'camping',
  'beach_access',
  'music_note',
  'headphones',
  'movie',
  'live_tv',
  'theater_comedy',
  'palette',
  'brush',
  'photo_camera',
  'celebration',
  'cake',
  'featured_seasonal_and_gifts',
  'redeem',
  'luggage',
  'hotel',
  'map',
  'place',
  'wifi',
  'smartphone',
  'bolt',
  'water_drop',
  'local_laundry_service',
  'dry_cleaning',
  'checkroom',
  'cleaning_services',
  'handyman',
  'build',
  'plumbing',
  'electrical_services',
  'kitchen',
  'cooking',
  'inventory_2',
  'subscriptions',
  'card_membership',
  'policy',
  'gavel',
  'volunteer_activism',
  'favorite',
  'star',
  'category',
  'label',
] as const;

/**
 * Labels FR supplémentaires (synonymes du quotidien) indexés par nom d’icône.
 * Complète le dictionnaire mot-à-mot généré, trop pauvre pour la recherche.
 */
export const ICON_EXTRA_LABELS: Readonly<Record<string, readonly string[]>> = {
  account_balance: ['banque', 'impôts', 'impot', 'taxes', 'fisc', 'administration'],
  account_balance_wallet: ['portefeuille', 'salaire', 'paie', 'revenus'],
  apartment: ['loyer', 'location', 'appart', 'logement'],
  attach_money: ['salaire', 'paie', 'argent', 'revenu', 'revenus'],
  auto_stories: ['livre', 'lecture', 'roman'],
  bakery_dining: ['boulangerie', 'pain', 'viennoiserie'],
  beach_access: ['plage', 'vacances', 'été'],
  bolt: ['électricité', 'electricite', 'énergie', 'edf', 'facture'],
  build: ['bricolage', 'travaux', 'réparation'],
  cake: ['anniversaire', 'gâteau', 'fête'],
  camping: ['camping', 'vacances', 'tente'],
  featured_seasonal_and_gifts: ['cadeau', 'présent', 'anniversaire', 'noël', 'noel', 'gift'],
  card_membership: ['abonnement', 'adhesion', 'cotisation', 'club'],
  celebration: ['fête', 'anniversaire', 'soirée', 'party'],
  checkroom: ['vêtements', 'vetements', 'habit', 'habits', 'mode'],
  child_care: ['enfant', 'enfants', 'bébé', 'bebe', 'nounou', 'crèche', 'creche'],
  child_friendly: ['enfant', 'enfants', 'bébé', 'bebe', 'famille'],
  cleaning_services: ['ménage', 'menage', 'nettoyer', 'femme de ménage'],
  coffee: ['café', 'cafe', 'boisson'],
  cooking: ['cuisine', 'cuisiner', 'recette'],
  cottage: ['loyer', 'maison', 'logement', 'vacances'],
  credit_card: ['carte', 'cb', 'bancaire', 'paiement'],
  currency_exchange: ['change', 'devise', 'forex', 'dollar'],
  dentistry: ['dentiste', 'dents', 'orthodontiste'],
  directions_bike: ['vélo', 'velo', 'cyclisme'],
  directions_bus: ['bus', 'car', 'transport'],
  directions_car: ['voiture', 'auto', 'véhicule', 'vehicule', 'permis'],
  directions_subway: ['métro', 'metro', 'rer', 'transport'],
  dry_cleaning: ['pressing', 'nettoyage', 'vêtements', 'vetements'],
  elderly: ['seniors', 'retraite', 'âgé', 'age'],
  electrical_services: ['électricité', 'electricite', 'électricien', 'electricien'],
  euro: ['euro', 'argent', 'monnaie'],
  ev_station: ['électrique', 'electrique', 'recharge', 'borne'],
  fastfood: ['fast food', 'burger', 'snack', 'junk food'],
  fitness_center: ['sport', 'salle', 'musculation', 'gym', 'fitness'],
  flight: ['avion', 'voyage', 'vol', 'aéroport', 'aeroport'],
  garage: ['garage', 'parking', 'voiture'],
  gavel: ['justice', 'avocat', 'tribunal', 'amende'],
  handyman: ['bricolage', 'travaux', 'réparation', 'artisan'],
  headphones: ['musique', 'casque', 'audio', 'écouteurs'],
  hiking: ['randonnée', 'randonnee', 'marche', 'nature'],
  home: ['maison', 'loyer', 'logement', 'domicile', 'chez soi'],
  hotel: ['hôtel', 'hotel', 'nuitée', 'nuitee', 'voyage', 'hébergement', 'hebergement'],
  icecream: ['glace', 'dessert', 'sorbet'],
  inventory_2: ['stock', 'carton', 'déménagement', 'demenagement'],
  kitchen: ['cuisine', 'électroménager', 'electromenager'],
  label: ['étiquette', 'tag', 'catégorie'],
  liquor: ['alcool', 'spiritueux', 'vin', 'bière', 'biere'],
  local_bar: ['bar', 'apéro', 'apero', 'boisson', 'alcool'],
  local_cafe: ['café', 'cafe', 'pause', 'boisson'],
  local_gas_station: ['essence', 'carburant', 'plein', 'station', 'diesel', 'sp95', 'sp98'],
  grocery: ['courses', 'supermarché', 'supermarche', 'épicerie', 'epicerie', 'alimentaire', 'magasin'],
  local_hospital: ['hôpital', 'hopital', 'urgence', 'santé', 'sante'],
  local_laundry_service: ['laverie', 'lessive', 'linge'],
  local_mall: ['centre commercial', 'shopping', 'magasin'],
  local_pizza: ['pizza', 'italien', 'restaurant'],
  local_taxi: ['taxi', 'vtc', 'uber', 'course'],
  luggage: ['bagages', 'valise', 'voyage', 'vacances'],
  lunch_dining: ['déjeuner', 'dejeuner', 'midi', 'repas'],
  dinner_dining: ['dîner', 'diner', 'soir', 'repas'],
  map: ['carte', 'itinéraire', 'itineraire', 'plan'],
  medical_services: ['santé', 'sante', 'médecin', 'medecin', 'docteur', 'soins'],
  medication: ['médicament', 'medicament', 'pharmacie', 'ordonnance', 'pilule'],
  menu_book: ['livre', 'lecture', 'recette', 'menu'],
  monitor_heart: ['cœur', 'coeur', 'santé', 'sante', 'cardio'],
  movie: ['film', 'cinéma', 'cinema', 'séance', 'seance'],
  music_note: ['musique', 'concert', 'chanson', 'audio'],
  payments: ['paiement', 'salaire', 'virement', 'dépense', 'depense'],
  pedal_bike: ['vélo', 'velo', 'cyclisme'],
  pets: ['animaux', 'chien', 'chat', 'animal', 'vétérinaire', 'veterinaire'],
  photo_camera: ['photo', 'appareil', 'souvenir'],
  place: ['lieu', 'adresse', 'emplacement', 'pin'],
  plumbing: ['plomberie', 'plombier', 'fuite', 'eau'],
  point_of_sale: ['caisse', 'paiement', 'tpe', 'carte'],
  policy: ['assurance', 'contrat', 'mutuelle', 'prévoyance', 'prevoyance'],
  pool: ['piscine', 'natation', 'baignade'],
  receipt_long: ['reçu', 'recu', 'facture', 'ticket', 'justificatif'],
  redeem: ['cadeau', 'récompense', 'recompense', 'bon'],
  request_quote: ['devis', 'facture', 'impôt', 'impot', 'taxes'],
  restaurant: ['restaurant', 'resto', 'manger', 'repas', 'sortie'],
  savings: ['épargne', 'epargne', 'économies', 'economies', 'livret', 'pel'],
  school: ['école', 'ecole', 'études', 'etudes', 'collège', 'college', 'lycée', 'lycee'],
  self_care: ['soin', 'bien-être', 'bien etre', 'beauté', 'beaute'],
  sell: ['vente', 'promo', 'soldes', 'prix'],
  shopping_bag: ['courses', 'sac', 'shopping', 'achat'],
  shopping_cart: ['courses', 'panier', 'caddie', 'supermarché', 'supermarche'],
  smartphone: ['téléphone', 'telephone', 'mobile', 'portable', 'iphone'],
  spa: ['spa', 'massage', 'détente', 'detente', 'bien-être'],
  sports_esports: ['jeu', 'jeux', 'gaming', 'console', 'vidéo', 'video'],
  sports_soccer: ['foot', 'football', 'sport', 'ballon'],
  store: ['magasin', 'boutique', 'commerce'],
  storefront: ['commerce', 'magasin', 'boutique', 'enseigne'],
  stroller: ['poussette', 'bébé', 'bebe', 'enfant'],
  subscriptions: ['abonnement', 'mensuel', 'récurrent', 'recurrent', 'netflix', 'spotify'],
  theater_comedy: ['théâtre', 'theatre', 'spectacle', 'humour'],
  train: ['train', 'sncf', 'ferroviaire', 'tgv', 'ter'],
  tram: ['tram', 'tramway', 'transport'],
  two_wheeler: ['moto', 'scooter', 'deux roues'],
  villa: ['maison', 'loyer', 'villa', 'logement'],
  volunteer_activism: ['don', 'charité', 'charite', 'association', 'bénévolat', 'benevolat'],
  water_drop: ['eau', 'facture', 'robinet'],
  wifi: ['internet', 'box', 'wifi', 'fibre', 'réseau', 'reseau'],
  work: ['travail', 'emploi', 'boulot', 'bureau', 'job'],
  live_tv: ['télé', 'tele', 'tv', 'série', 'serie'],
  palette: ['art', 'peinture', 'dessin', 'créatif', 'creatif'],
  brush: ['peinture', 'art', 'dessin'],
  star: ['favori', 'étoile', 'etoile', 'important'],
  favorite: ['cœur', 'coeur', 'amour', 'favori'],
  category: ['catégorie', 'categorie', 'dossier', 'type'],
};
